name: Lint

on:
  pull_request:
    paths-ignore:
      - 'README.*'
  push:
    branches:
      - master
    paths-ignore:
      - 'README.*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    uses: emacs-twist/internal/.github/workflows/check.yml@3dbe7586aaadb24d129484d386cc710abb247449
    with:
      package: linters
