name: Smoke test

on:
  push:
    paths:
    - 'flake.lock'
    - 'pkgs/**'
    - 'modules/**'
    - 'test/**'
    - '.github/workflows/smoke-test.yml'
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          accept-flake-config = true

    - name: Update the flake inputs for the test
      run: |
        nix develop -c just local-update-flake
      working-directory: test

    - name: Test
      working-directory: test
      run: nix develop -c just test

    - run: nix flake show
