name: Smoke test

on:
  push:
    paths:
    - 'flake.lock'
    - 'pkgs/**'
    - 'test/**'
    - '.github/workflows/smoke-test.yml'
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18

    - uses: cachix/cachix-action@v12
      with:
        name: akirak
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        extraPullNames: emacs-ci
        skipPush: true

    - name: Update the flake inputs for the test
      run: nix flake update --inputs-from $PWD/.. --override-input twist $PWD/..
      working-directory: test

    - name: Check the precondition
      working-directory: test
      run: |
        make clean
        [[ ! -f lock/flake.nix ]]
        [[ ! -f lock/flake.lock ]]
        [[ ! -f lock/archive.lock ]]

    - name: Build the configuration without a lock file (which should fail)
      id: no-lock
      working-directory: test
      run: nix build --dry-run
      continue-on-error: true

    - name: Pure evaluation without the lock file must fail
      if: ${{ steps.no-lock.outcome == 'success' }}
      run: exit 1

    - name: Lock the ELPA packages
      working-directory: test
      run: nix run .#update --impure

    - name: Generate the lock file for MELPA packages
      working-directory: test
      run: nix run .#lock --impure

    - name: The lock file exists
      working-directory: test
      run: |
        [[ -s lock/archive.lock ]]
        [[ -s lock/flake.nix ]]
        [[ -s lock/flake.lock ]]

    - name: Build the configuration with the generated lock file
      working-directory: test
      run: nix build --dry-run

    - name: Get the system
      id: system
      run: |
        system=$(nix eval --impure --expr builtins.currentSystem)
        echo "emacs=packages.$system.emacs" >> $GITHUB_OUTPUT

    - run: |
        nix eval --json .#${{ steps.system.outputs.emacs }}.initFiles \
        | jq
      working-directory: test

    - run: |
        nix eval --json .#${{ steps.system.outputs.emacs }}.packageInputs \
        | jq
      working-directory: test

    - run: |
        nix eval --json .#${{ steps.system.outputs.emacs }}.elispPackages.magit \
        | jq
      working-directory: test

    - run: nix flake show
