name: Unit tests

on:
  push:
    paths:
    - 'flake.lock'
    - 'pkgs/build-support/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Run unit tests
      run: |
        set -euo pipefail
        nix-instantiate --strict --eval --json pkgs/build-support/**/test*.nix \
        | jq
